# Generated by Django 4.1.7 on 2023-04-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManagement', '0004_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_home',
            field=models.BooleanField(default=False),
        ),
    ]
