# Generated by Django 4.1.7 on 2023-04-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManagement', '0005_article_main_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_icon',
            field=models.ImageField(blank=True, help_text='Please Upload the image size of 154 * 125', null=True, upload_to='static/articleicon/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_home_image',
            field=models.ImageField(blank=True, help_text='Please Upload the image size of 756 * 411', null=True, upload_to='static/articlehome/'),
        ),
    ]
