# Generated by Django 4.1.7 on 2023-04-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManagement', '0006_alter_article_image_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_icon',
            field=models.ImageField(blank=True, help_text='Please Upload the image size of 154 * 125', null=True, upload_to='articleicon/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_home_image',
            field=models.ImageField(blank=True, help_text='Please Upload the image size of 756 * 411', null=True, upload_to='articlehome/'),
        ),
    ]
