# Generated by Django 4.1.7 on 2023-04-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManagement', '0007_alter_article_image_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='ok', unique=True),
            preserve_default=False,
        ),
    ]
